[[getting-started]]
= Getting Started

Silverblue is designed to be easy and straightforward to use, and specialist 
knowledge should generally not be required. However, Silverblue is built 
differently from other operating systems, and there are therefore some things 
that it is useful to know.

Because Silverblue is immutable, software has to be installed on it so that it 
is isolated from the host system. This can be done in three ways:

- Flatpak apps: this is the primary way that apps get installed on Silverblue.
- Containers: can be installed and used for development
- Toolbox containers: a special kind of container tailored to provide a 
development environment

The following sections provide more information on using each of these methods.

The other method of installing software on Silverblue is package layering. 
This is different from the other methods, and goes against the general 
principle of immutability. Package layering adds individual packages to the 
Silverblue system, and in so doing modifies the operating system. 

[[flatpak]]
== Flatpak apps

Flatpak is the primary way that apps get installed on Silverblue. It is a 
next-generation application framework that provides a number of advantages. For 
information about Flatpak, see http://flatpak.org[flatpak.org].

Flatpak works out of the box in Fedora Silverblue, and Fedora provides a small 
(but growing) collection of apps that can be installed.

https://flathub.org/home[Flathub] is a large repository of Flatpak apps that 
can also be used. Setup for Silverblue is just a few clicks - just follow the 
https://flatpak.org/setup/Fedora/[standard Fedora instructions].

=== Installing apps with Flatpak

Flatpak is fully integrated into Fedora Workstation, and apps can be browsed, 
search and installed using the Software app.

Alternatively, it is possible to use `flatpak` from the command line. See the 
http://docs.flatpak.org/en/latest/using-flatpak.html[Flatpak documentation] for 
how to use this.

[[toolbox-and-containers]]
== Toolbox and containers

As an immutable host, Silverblue is an excellent platform for container-based 
development. For working with containers, buildah and podman are recommended.

Silverblue also comes with the _toolbox_ utility, which uses containers to 
provide an environment where development tools and libraries can be installed 
and used. The link:toolbox[toolbox page] provides more details on this.

[[package-layering]]
== Package layering

Package layering works by modifying your Silverblue installation. As the name 
implies, it works by modifying the packages from which Silverblue is composed. 
Any software package that is provided by Fedora can be installed on Silverblue 
using this method.

A Silverblue installation with packages layered on top loses some of the 
advantages of immutability. With layering in place, the system is no longer 
identical to other installations, and is not as robust (particularly with 
regards to OS updates).

Nevertheless, package layering can be a useful option, for installing 
software that might not be available through other means, or installing 
software that, for technical reasons, needs to be part of the host operating 
system.

Typically, the system must be rebooted after a package has been layered. This 
is an obvious practical disadvantage compared with installing Flatpaks or 
containers.

Package layering is typically only done from the command line. However, the 
Software application does rely on it for installing a small number of apps 
that are currently difficult to install as Flatpakts.

=== Installing packages

Packages can be installed on Silverblue using:

`$ rpm-ostree install <package name>`

This will download the package and any required dependencies, and recompose 
your Silverblue image with them. `rpm-ostree` uses standard Fedora package 
names, which can be searched using DNF (this is not available on a Silverblue 
host, but can be used in a toolbox).

Once a package has been installed in this manner, it will be kept up-to-date 
as new versions are released and as the base operating system is updated.

=== Removing and replacing packages

A package can be removed from a Silverblue installation using:

`$ rpm-ostree override remove <package name>`

The same `rpm-ostree override` command can be used to replace a package with a 
different version. For example:

`$ rpm-ostree override replace <path to package>`

Removing and replacing packages is not generally recommended. For more 
information, see the 
https://rpm-ostree.readthedocs.io/en/latest/manual/administrator-handbook/[rpm-ostree documentation].
