= {variant-name} User Guide

Welcome to the {variant-name} user guide!

image::silverblue-logo.svg[{variant-name} logo]

_{variant-name}_ is an immutable desktop operating system.
It aims to be extremely stable and reliable.
It also aims to be an excellent platform for developers and for those using container-focused workflows.

[[introduction]]
== Introduction to {variant-name}

{variant-name} is a variant of Fedora Workstation.
It looks, feels and behaves like a regular desktop operating system, and the experience is similar to what you find with using a standard Fedora Workstation.

However, unlike other operating systems, {variant-name} is immutable.
This means that every installation is identical to every other installation of the same version.
The operating system that is on disk is exactly the same from one machine to the next, and it never changes as it is used.

{variant-name}'s immutable design is intended to make it more stable, less prone to bugs, and easier to test and develop.
Finally, {variant-name}'s immutable design also makes it an excellent platform for containerized applications as well as container-based software development.
In each case, applications (apps) and containers are kept separate from the host system, improving stability and reliability.

{variant-name}'s core technologies have some other helpful features.
OS updates are fast and there's no waiting around for them to install: just reboot as normal to start using the next version.
With {variant-name}, it is also possible to roll back to the previous version of the operating system, if something goes wrong.

[[this-guide]]
== About this guide

In most cases, {variant-name} behaves like a standard Fedora Workstation installation, and the https://docs.fedoraproject.org/[standard Fedora documentation] can be used.
This guide covers those areas where {variant-name} differs from a standard Fedora Workstation, including:

* xref:installation.adoc[OS installation]
* xref:getting-started.adoc[Installing apps and software]
* xref:updates-upgrades-rollbacks.adoc[OS upgrades and rollbacks]

The primary audience for these docs are new users, who aren't expected to have specialist knowledge or technical knowledge about {variant-name}'s internals.
However, some background xref:technical-information.adoc[technical information] is provided, for those who are interested and want to learn more.
