= Tips and Tricks

== Working with Toolbx

=== Running applications from inside Toolbx on the host

This can be necessary if you want to interact with tools available from the
host, for example `podman`, `nmcli` or `rpm-ostree` without leaving the Toolbx
container in between. You can use `flatpak-spawn`, included in the base
installation for this:

  $ flatpak-spawn --host podman --help

If the application you want to call requires `sudo` access, the `-S` option must
be supplied to `sudo` like below:

  $ flatpak-spawn --host sudo -S rpm-ostree status

If you find yourself using commands like these frequently to access e.g. the
flatpak command from inside the Toolbx container, you can create yourself a
short custom wrapper script (*inside the Toolbx container*):

  [toolbx]$ echo -e '#!/bin/sh\nexec /usr/bin/flatpak-spawn --host flatpak "$@"' | sudo tee /usr/bin/flatpak 1>/dev/null && sudo chmod +x /usr/bin/flatpak

[NOTE]
====
If the command above results in an error saying `tee: /usr/bin/flatpak:
Read-only file system`, you tried to overwrite the actual `flatpak` executable
on your host system. Please run this command in a Toolbx container!
====


=== Finding out if you are currently in a Toolbx container

If you frequently make use of Toolbx to perform various tasks and use multiple
Toolbx containers it can be hard to keep track of whether you are currently
executing commands on the host or in a Toolbx container. Furthermore, there is
currently no command to tell you in which Toolbx container you are working.

To alleviate this, you can add the following shell alias at the end of your
`~/.bashrc`:

  alias istoolbx='[ -f "/run/.toolboxenv" ] && grep -oP "(?<=name=\")[^\";]+" /run/.containerenv'

When you open a new shell, you now have access to the new command `istoolbx`.
This will behave as follows

* When run from the host, returns an exit code of 1
* When run from a Toolbx container, returns an exit code of 0 and prints the
  current Toolbx containers name to the console



== Working with `ostree`/`rpm-ostree`

=== Tracking changes to the base OS

Some directories in `ostree`-based operating systems are writable by the user,
like `/etc`. You can get a quick overview of the files changed under `/etc`
using the following command:

  $ sudo ostree admin config-diff

To get a more elaborate diff, you can use something like this:

  $ sudo diff -yrW200 --suppress-common-lines --color=always /usr/etc /etc 2>/dev/null

NOTE: This works because ostree keeps an unmodified copy of the `/etc` directory
      under `/usr/etc`. All of your changes go to `/etc` directly.



== Working with Flatpak applications

=== Directly accessing Flatpak applications from the CLI

The most noticable change when using Flatpak applications instead of
conventional installations is that the applications cannot be directly called
from the CLI any more, like so:

  $ evince
  bash: command not found: evince

Instead, one can call them like this:

  $ flatpak run org.gnome.Evince

In addition, most Flatpak applications export their internal binaries under an
installation-dependent location:

* For Flatpak applications installed from `system` remotes, these can be found
  under `/var/lib/flatpak/exports/bin/`
* For Flatpak applications installed from `user` remotes, these can be found
  under `$HOME/.local/share/flatpak/exports/bin/`

[NOTE]
====
If you're unsure to which installation a Flatpak application belongs, you can
use this command to print it out:
        
  $ flatpak list --app --columns=name,installation
====

You can then either add these directories to your `$PATH`:

  $ org.gnome.Evince

or setup shell `alias`es as needed to make them available to the CLI like so:

  $ alias evince="flatpak run org.gnome.Evince"
    # or alias evince="org.gnome.Evince"
  $ evince

