[[updates-upgrades-rollbacks]]
= Updates, Upgrades & Rollbacks

Installing updates with Silverblue is easy and fast (much faster than other
operating systems). It also has a special rollback feature, in case anything
goes wrong.

[[updating]]
== Updating Silverblue

OS updates in Silverblue are fully integrated into the desktop; you will be
automatically notified when an update is available. The standard behavior is to
automatically download the update (this can be changed from the update
preferences in Software).

Once an update is ready, it is just a matter of rebooting to start using the
new version. There is no waiting for the update to be installed during this
reboot.

If you'd prefer, it is also possible to update using the command line. To do
this, run:

 $ rpm-ostree upgrade

This will check for new updates and download and install them if they are
available. Alternatively, to check for available updates without downloading
them, run:

 $ rpm-ostree upgrade --check

[[upgrading]]
== Upgrading between major versions

Upgrading between major versions (such as from Fedora 34 to Fedora 35) can be
completed using the Software application. Alternatively, Silverblue can be
upgraded between major versions using the `ostree` command.

First, verify the branch is available. You can print all available branches
with this command:

 $ ostree remote refs fedora

After you verify the name of your branch, you are ready to proceed. For
example, to upgrade to Silverblue 35, the command is:

NOTE: Currently, the default remote for Silverblue 35 is named `fedora`. If
this is not the case for your system, you can find out the remote name by
issuing: `ostree remote list`.

 $ rpm-ostree rebase fedora:fedora/35/x86_64/silverblue

The process is very similar to a system update: the new OS is downloaded and
installed in the background, and you just boot into it when it is ready.

[[rolling-back]]
== Rolling back

Silverblue keeps a record of the previous OS version, which can be switched to
instead of the latest version. While this shouldn't usually be necessary, it
can be helpful if there is a problem with an update or an upgrade (rollbacks
work the same way for both), as well as for development purposes.

There are two ways to roll back to the previous version:

. Temporary rollbacks: to temporarily roll back to a previous version, simply
  reboot and select the previous version from the boot menu (often known as the
  grub menu).
. Permanent rollbacks: to permanently switch back to the previous deployment,
  use the `rpm-ostree rollback` command.

After rolling back, you will technically be on an old OS version, and may be
prompted to update. Updating will undo the rollback, so should be avoided if
you want the rollback to stay in effect.
