[[updates-upgrades-rollbacks]]
= Updates, Upgrades & Rollbacks

Installing updates with {variant-name} is easy and fast.
It also has a special rollback feature, in case anything goes wrong.
Additionally, you can choose to have multiple versions of your operating system installed at all times, and you can choose which one to boot into whenever you start up your system.

[[updating]]
== Updating {variant-name}

OS updates are fully integrated into the desktop; you will be automatically notified when an update is available.
The standard behavior is to automatically download the update (this can be changed from the update preferences in Software).

Once an update is ready, it is just a matter of rebooting to start using the new version.
There is no waiting for the update to be installed during this reboot.

If you'd prefer, it is also possible to update using the command line.
To do this, run:

 $ rpm-ostree upgrade

This will check for new updates and download and install them if they are available.
Alternatively, to check for available updates without downloading them, run:

 $ rpm-ostree upgrade --check

[[upgrading]]
== Upgrading between major versions

Upgrading between major versions (such as from Fedora {version-oldstable} to Fedora {version-stable}) can be completed using the {update-application} application.
Alternatively, {variant-name} can be upgraded between major versions using the `rpm-ostree` command.

[WARNING]
====
Skipping major releases is currently untested and is thus not supported.
You should update only one major release at a time, i.e. from Fedora {version-oldstable} to {version-stable}, etc.
====

First, make sure that you are running the latest update for the current version:

[source,bash]
----
$ rpm-ostree upgrade
----

Reboot your system if needed.
Then, verify that the branch for the next major version is available.
You can print all available branches for {variant-name} with this command:

[source,bash,subs="attributes"]
----
$ ostree remote refs fedora | grep {variant} | grep $(uname -m)
----

After you've verified the name of your branch, you are ready to proceed.
For example, to upgrade to {variant-name} {version-stable}, the command is:

[source,bash,subs="attributes"]
----
$ rpm-ostree rebase fedora:fedora/{version-stable}/x86_64/{variant}
----

NOTE: Currently, the default remote for {variant-name} {version-stable} is named `fedora`.
      If this is not the case for your system, you can find out the remote name by issuing: `ostree remote list`.

The process is very similar to a system update: the new OS is downloaded and installed in the background, and you just boot into it when it is ready.

Additionally, you can choose to rebase to a different variant of Fedora Atomic, like for example {alternative-name}.
{alternative-name} is similar to {variant-name}, except for the fact that it uses the {alternative-desktop} instead of the default {variant-desktop}.

What this means is, you can rebase to {alternative-name} to try it out, without ever touching your current system.
Because the two system images are isolated from eachother, the two desktop environments will never be installed at the same time.
All of your flatpak apps and /home files will stay persistent between rebases.
Same applies for testing out the bleeding-edge version of {variant-name}, which is Rawhide.

If you decide to rebase, make sure to xref:faq.adoc#pinning[pin] your current deployment, so you don't accidentaly lose it (by default, only the two most recent deployments are kept).

[[rolling-back]]
== Rolling back

{variant-name} keeps a record of the previous OS version, which can be switched to instead of the latest version.
While this shouldn't usually be necessary, it can be helpful if there is a problem with an update or an upgrade (rollbacks work the same way for both), as well as for development purposes.

There are two ways to roll back to the previous version:

. Temporary rollbacks: to temporarily roll back to a previous version, simply reboot and select the previous version from the boot menu (often known as the grub menu).
. Permanent rollbacks: to permanently switch back to the previous deployment, use the `rpm-ostree rollback` command.

After rolling back, you will technically be on an old OS version, and may be prompted to update.
Updating will undo the rollback, so should be avoided if you want the rollback to stay in effect.

`rpm-ostree` only keeps one rollback version available by default.
If you want to rollback to another version than the one currently available on your system, you can do so with the following commands:

. Pull the ostree commit log from the remote repository:
+
[source,bash,subs="attributes"]
----
$ sudo ostree pull --commit-metadata-only --depth=10 fedora fedora/{version-stable}/x86_64/{variant}
----

. Display the log:
+
[source,bash,subs="attributes"]
----
$ ostree log fedora:fedora/{version-stable}/x86_64/{variant}
----

. Deploy a specific commit:
+
[source,bash,subs="attributes"]
----
$ rpm-ostree deploy {version-stable}.20230716.0
----

Note that this will deploy the exact version as requested and will not include overlayed packages and other changes.

[[removing-and-pinning-deployments]]
== Removing and pinning deployments

Deployments are automatically removed as updates occur.
However, if you want to manually remove all previous or pending deployments to free up disk space, you can do so using the `rpm-ostree cleanup` command.
Moreover, if you want to keep specific deployments from being removed by the cleanup command, you can pin them, this will be discussed later.

Remove previous deployments:
----
$ rpm-ostree cleanup --rollback
----
Remove pending deployments:
----
$ rpm-ostree cleanup --pending
----

Specific deployments can be pinned so they don't get removed by the `rpm-ostree cleanup` command.
Deployments can also be unpinned so they can be removed normally.
You can, for example, pin deployments which you deem as stable on your system, so you will have a guaranteed fallback if a future update introduces any regressions or bugs.

To pin or unpin a deployment, you need to know the index number of that deployment.

Check the index number of deployments:
----
$ rpm-ostree status -v
----

Pin a deployment:
----
$ sudo ostree admin pin 0
----

Unpin a deployment:
----
$ sudo ostree admin pin --unpin 0
----
