[[updates-upgrades-rollbacks]]
= Updates, Upgrades & Rollbacks

Installing updates with {variant-name} is easy and fast.
It also has a special rollback feature, in case anything goes wrong.
Additionally, you can choose to have multiple versions of your operating system installed at all times, and you can choose which one to boot into whenever you start up your system.

[[updating]]
== Updating {variant-name}

OS updates in {variant-name} are fully integrated into the desktop; you will be automatically notified when an update is available.
The standard behavior is to automatically download the update (this can be changed from the update preferences in Software).

Once an update is ready, it is just a matter of rebooting to start using the new version.
There is no waiting for the update to be installed during this reboot.

If you'd prefer, it is also possible to update using the command line.
To do this, run:

 $ rpm-ostree upgrade

This will check for new updates and download and install them if they are available.
Alternatively, to check for available updates without downloading them, run:

 $ rpm-ostree upgrade --check

[[upgrading]]
== Upgrading between major versions

Upgrading between major versions (such as from Fedora 35 to Fedora 36) can be completed using the Software application.
Alternatively, {variant-name} can be upgraded between major versions using the `ostree` command.

First, verify the branch is available.
You can print all available branches with this command:

[source,bash,subs="attributes"]
----
$ ostree remote refs fedora | grep {variant}
----

After you verify the name of your branch, you are ready to proceed.
For example, to upgrade to {variant-name} {version}, the command is:

NOTE: Currently, the default remote for {variant-name} {version} is named `fedora`.
      If this is not the case for your system, you can find out the remote name by issuing: `ostree remote list`.

[source,bash,subs="attributes"]
----
$ rpm-ostree rebase fedora:fedora/{version}/x86_64/{variant}
----

The process is very similar to a system update: the new OS is downloaded and installed in the background, and you just boot into it when it is ready.

Additionally, you can choose to rebase to a different immutable variant of Fedora, like for example Fedora Kinoite.
Fedora Kinoite is similar to {variant-name}, except for the fact that it uses the KDE Plasma desktop environment instead of the default GNOME desktop environment.

What this means is, you can rebase to Fedora Kinoite to try it out, without ever touching your current system.
Because the two system images are isolated from eachother, the two desktop environments will never be installed at the same time.
All of your flatpak apps and /home files will stay persistent between rebases.
Same applies for testing out the bleeding-edge version of {variant-name}, which is Rawhide.

If you decide to rebase, make sure to https://docs.fedoraproject.org/en-US/fedora-silverblue/faq/#_about_using_silverblue[pin] your current deployment, so you don't accidentaly lose it (by default, only the two most recent deployments are kept).

[[rolling-back]]
== Rolling back

{variant-name} keeps a record of the previous OS version, which can be switched to instead of the latest version.
While this shouldn't usually be necessary, it can be helpful if there is a problem with an update or an upgrade (rollbacks work the same way for both), as well as for development purposes.

There are two ways to roll back to the previous version:

. Temporary rollbacks: to temporarily roll back to a previous version, simply reboot and select the previous version from the boot menu (often known as the grub menu).
. Permanent rollbacks: to permanently switch back to the previous deployment, use the `rpm-ostree rollback` command.

After rolling back, you will technically be on an old OS version, and may be prompted to update.
Updating will undo the rollback, so should be avoided if you want the rollback to stay in effect.
