[[updates-upgrades-rollbacks]]
= Updates, Upgrades & Rollbacks

Updating Silverblue is quicker and more reliable when compared with other 
operating systems.

[[updating]]
== Updating Silverblue

OS updates in Silverblue are fully integrated into the desktop: you will be 
notified when an update is available and it will be automatically downloaded, 
if this is your preference.

Once an update is ready, it is just a matter of rebooting to start using the 
new version. There is no waiting for the update to be installed during this 
reboot.

If you'd prefer, it is also possible to update using the command line. To do 
this, run:

`$ rpm-ostree upgrade`

Alternatively, to check for available updates without downloading them, run:

`& rpm-ostree upgrade --check`

[[upgrading]]
== Upgrading between major versions

Upgrading between major versions (such as from Fedora 29 to Fedora 30) is not 
fully integrated into Silverblue at this time. However, Silverblue can be 
upgraded from the command line, using the `ostree` command.

To upgrade from Fedora Silverblue 29 to Silverblue 30, run:

....
$ sudo ostree remote gpg-import fedora-workstation -k /etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-30-primary
$ rpm-ostree rebase fedora-workstation:fedora/30/x86_64/silverblue
....

The process is very similar to a system update: the new OS is downloaded and
installed in the background, and you just boot into it when it is ready.

[[rolling-back]]
== Rolling back

Silverblue keeps a record of the previous OS version, which can be switched to 
instead of the latest version. While this shouldn't usually be necessary, it 
can be helpful if there is a problem with an update or an upgrade (roll backs 
work the same way for both), as well as for development purposes.

There are two ways to roll back to thae previous version:

. Temporary rollbacks: to temporarily roll back to a previous version, simply 
reboot and select the previous version from the boot menu (often known as the 
grub menu).
. Permanant rollbacks: to permanently switch back to the previous deployment, 
use the `rpm-ostree rollback` command.

After rolling back, you will technically be on an old OS version, and may be 
prompted to update.