site:
  title: Local Preview
  start_page: fedora-silverblue::index.adoc
content:
  sources:
   - url: .
     branches: HEAD
ui:
  bundle:
    url: https://asamalik.fedorapeople.org/ui-bundle.zip
    snapshot: true
  default_layout: with_menu
output:
  clean: true
  dir: ./public
  destinations:
  - provider: archive
runtime:
  fetch: true
  cache_dir: ./cache
asciidoc:
  attributes:
    variant: silverblue
    variant-name: Silverblue
    website: https://silverblue.fedoraproject.org/
    issue-tracker: https://github.com/fedora-silverblue/issue-tracker/issues
    docs-url: https://docs.fedoraproject.org/en-US/fedora-silverblue/
    docs-src: https://github.com/fedora-silverblue/silverblue-docs
    docs-issue: https://github.com/fedora-silverblue/silverblue-docs/issues
    discussion-forum: https://discussion.fedoraproject.org/c/desktop/silverblue
